### ISSUE TITLE
Major update

### ISSUE THREAD

**Issue by 75py** [75py/Aplin#123]
残課題

must
* .travis.yml
* test
* app icon
* share
* google
* license

should
* display item

**Comment by IzzySoft** [comment]
would be nice if

* some trackers could be removed (maybe Firebase and Firebase Analytics?) or replaces with less invasive ones (ACRA?)
* there's be a FOSS build without proprietary elements (GMS, Firebase, Google Ads) so the app would qualify for F-Droid

😃 just suggesting 😉

**Comment by 75py** [comment]
Firebase Analytics was removed in version 5.0.0.

**Comment by IzzySoft** [comment]
Thanks – and glad to see the project is still alive! Apologies for the late reaction (somehow Github notifications no longer reached me, which is hopefully fixed by now). Can you please attach the (signed) APKs to their corresponding releases again (starting with the most recent one is fully sufficient, no need to have it on the older ones now)?
